apiVersion: apps/v1
kind: Deployment
metadata:
  name: drupal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drupal
  template:
    metadata:
      labels:
        app: drupal
    spec:
      initContainers:
        - name: init-sites
          image: drupal:latest
          command: ["sh", "-c", "cp -a /var/www/html/sites/. /sites && chown -R www-data:www-data /sites"]
          volumeMounts:
            - name: drupal-sites
              mountPath: /sites
      containers:
        - name: drupal
          image: drupal:latest
          env:
            - name: DRUPAL_DB_HOST
              value: mysql 
            - name: DRUPAL_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_DATABASE
            - name: DRUPAL_DB_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_USER
            - name: DRUPAL_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD
          ports:
            - containerPort: 80
          volumeMounts:
            - name: drupal-sites
              mountPath: /var/www/html/sites
      volumes:
        - name: drupal-sites
          persistentVolumeClaim:
            claimName: pvc-drupal-sites 

